######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 9 02:38:19 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG -= qt
OBJECTS_DIR = obj

# Input
HEADERS += Org.hxx  Ren.hxx
SOURCES += main.cxx Org.cxx Ren.cxx
