######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 1 19:16:35 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lsqlite3
CONFIG -= qt
OBJECTS_DIR = obj

# Input
HEADERS += ../DB.sqlite3.hxx
SOURCES += db_tool.cxx ../DB.sqlite3.cxx
